from .image_directory_nodes import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .image_directory_nodes import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .video_directory_nodes import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .video_directory_nodes import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**IMAGE_NODE_CLASS_MAPPINGS, **VIDEO_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**IMAGE_NODE_DISPLAY_NAME_MAPPINGS, **VIDEO_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']